// GENERATED — do not edit. Regenerated by the `regenerate-registry`
// workflow node by scanning src/<Slug>/index.ts files.
import type React from 'react';

type CompMeta = {
  id: string;
  component: React.ComponentType<any>;
  width: number;
  height: number;
  fps: number;
  durationInFrames: number;
  defaultProps?: Record<string, unknown>;
  calculateMetadata?: any;
};

import aidoesntmakepeoplestupid_meta from './AIDoesntMakePeopleStupid';
import whatisdriver_meta from './WhatIsDriver';
import whyreflectiswhatotherframeworksmiss_meta from './WhyReflectIsWhatOtherFrameworksMiss';

const entries: CompMeta[] = [
  aidoesntmakepeoplestupid_meta,
  whatisdriver_meta,
  whyreflectiswhatotherframeworksmiss_meta,
];

export default entries;
